AdminPanel/urls.py
from django.urls import path , include
from . import views
app_name="AdminPanel"
urlpatterns = [
	path('',views.login_admin,name='login_admin'),
	path('main/',views.main_admin,name='main_admin'),
	path('upload-movies/',views.upload_movies,name='upload_movies'),
	path('upload-series/',views.upload_series,name='upload_series'),
	path('add-info-series/',views.add_info_series,name='add_info_series'),
	path('add-info-movies/',views.add_info_movies,name='add_info_movies')
]

StreamServer/urls.py
from django.contrib import admin
from django.urls import path , include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('WatchMovie.urls')),
    path('admin-panel/',include('AdminPanel.urls')),
    path('series/',include('WatchSeries.urls'))
]

WatchMovie/urls.py
from django.urls import path,re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name='WatchMovie'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.stream_movie,name='stream_movie'),
    path('search/',views.search_movie,name="search_movie")
]+ static(settings.MOVIES_URL, document_root=settings.MOVIES_ROOT)

WatchSeries/urls.py
from django.urls import path,re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name='WatchSeries'
urlpatterns = [
    path('',views.series,name='series'),
    path('episodes/<int:id_series>',views.episodes,name='episodes'),
    path('stream/<int:id_ep>',views.stream_series,name='stream_series'),
]+ static(settings.SERIES_URL, document_root=settings.SERIES_ROOT)

AdminPanel/models.py
from django.db import models
from WatchMovie.models import Movie

DISABLE = 0
INSERT = 1
ENABLE = 2

ACTIONS = [[DISABLE,'Disabilitato'],
		[INSERT,'Inserito'],
		[ENABLE,'Abilitato']]

class MoviesLog(models.Model):
	
	id_movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
	action = models.IntegerField(choices=ACTIONS)

WatchMovie/models.py
from django.db import models

class Actor(models.Model):
	name = models.CharField(max_length=50)
	surname = models.CharField(max_length=50)

class Movie(models.Model):
	title = models.CharField(max_length=50)
	original_title = models.CharField(max_length=50,null=True)
	ext = models.CharField(max_length=10)
	id_imdb = models.CharField(max_length=30,blank=True)
	actor = models.ManyToManyField(Actor,related_name='movieactor',blank=True)
#######data reperibile da wikipedia / omdb############
	img = models.CharField(max_length=255,blank=True)
	img_ext = models.CharField(max_length=10,blank=True)
	year = models.CharField(max_length=15,blank=True)
	plot = models.TextField(blank=True)
	runtime = models.CharField(max_length=15,blank=True)
	disabled = models.BooleanField(default=False)

	#crearea tabella N a N e usare il trought
	#other data about film 

WatchSeries/models.py
from django.db import models
from WatchMovie.models import Actor

class Series(models.Model):
	title = models.CharField(max_length=50)
	title_imdb = models.CharField(max_length=50,blank=True)
	id_imdb = models.CharField(max_length=30,blank=True)
	img = models.CharField(max_length=50,blank=True)
	year = models.CharField(max_length=15,blank=True)
	plot = models.TextField(blank=True)
	actor = models.ManyToManyField(Actor,related_name='seriesactor')

class Episode(models.Model):
	num = models.IntegerField()
	title = models.CharField(max_length=70)
	ext = models.CharField(max_length=10)
	season = models.IntegerField()
	series = models.ForeignKey(Series,on_delete=models.CASCADE)

AdminPanel/forms.py
from django import forms

class Login(forms.Form):

	widgets = {
	'password': forms.PasswordInput(),	
	}
	username = forms.CharField(label='Nome utente')
	password = forms.CharField(label='Password' , widget=forms.PasswordInput)

WatchMovie/forms.py
from django import forms

class Search(forms.Form):
	title = forms.CharField(label='Cerca per Titolo')

AdminPanel/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import Login
from django.contrib.auth import authenticate, login as login_auth
from django.contrib.auth.decorators import login_required
from django.conf import settings
import os
import pathlib
from WatchMovie.models import Movie
from .UpdateDb import updatedbmovies


def login_admin(request):
	if request.method == 'POST':
		form = Login(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(request,username=username,password=password)
			if user is not None:
				login_auth(request,user)
				return redirect('AdminPanel:main_admin')
			else:
				form = Login()
				msg = "Errore nell'autenticazione : Username e/o password sbagliati"
				return render(request, 'AdminPanel/login.html',{'form':form,'msg':msg})

		else:
			form = Login()
			msg = "Form non valido"
			return render(request, 'AdminPanel/login.html',{'form':form,'msg':msg})

	else:
		if request.user.is_authenticated:
			return render(request,'AdminPanel/main_admin.html')
		form = Login()
	return render(request, 'AdminPanel/login.html', {'form': form})

@login_required
def main_admin(request):
	return render(request,'AdminPanel/main_admin.html')

@login_required
def upload_movies(request):
	res = updatedbmovies.insert_movies_and_id_imdb()
	return render(request, 'AdminPanel/main_admin.html',res)

@login_required
def upload_series(request):
	res = updatedb.upload_series()
	return render(request, 'AdminPanel/main_admin.html',res)

@login_required
def add_info_movies(request):
	res = updatedbmovies.add_info_movies()
	return render(request,'AdminPanel/main_admin.html',res)

@login_required
def add_info_series(request):
	res = updatedb.add_info_series()
	return render(request,'AdminPanel/main_admin.html',res)

WatchMovie/views.py
from django.shortcuts import render
from .models import Movie
from .forms import *
from django.conf import settings
from django.db.models import CharField, Value as V
from django.db.models.functions import Concat
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import os

##### views #####
def index(request):
	form = Search()
	return render(request,'movies/index.html',{'form':form})

def search_movie(request):

	title=request.GET.get('title')
	page = request.GET.get('p')
	if title:
		movies = Movie.objects.filter(title__contains=title,disabled=False).values('id','title','img','runtime')
		paginator = Paginator(movies,8)
		movies = paginator.get_page(page)
		return render(request,'movies/search.html',{'movies':movies,'search':title})

	else:
		movies = Movie.objects.filter(disabled=False).values('id','title','img','runtime')
		paginator = Paginator(movies,8)
		if not page:
			page = 1
		movies = paginator.get_page(page)
	return render(request,'movies/all.html',{'movies':movies, 'search':title})

def stream_movie(request,movie_id):
	film = None
	if movie_id:
		film = Movie.objects.get(id=movie_id)
		title = film.title.replace(" ","_")
		ext = film.ext
		link = os.path.join(settings.MOVIES_URL_STREAM,title+ext)
	return render(request,'movies/stream.html',{'film':film,'link':link})

WatchSeries/views.py
from django.shortcuts import render,reverse
from .models import *
from django.core.paginator import Paginator
import os
from django.conf import settings

def series(request):
	page = request.GET.get('p')
	if not page:
		page=1

	series = Series.objects.all().values('id','title','img','year')
	paginator = Paginator(series,5)
	series_paginated = paginator.get_page(page)

	return render(request,'series/series.html',{'series':series_paginated})

def episodes(request,id_series):
	series = Series.objects.get(id=id_series)
	seasons = Episode.objects.filter(series=series).values('season').order_by('season').distinct()
	arr=[]
	print(seasons)
	for i in seasons:
		episodes = (Episode.objects.filter(series=series,season=i['season']).order_by('num')
		.values('id','title','num','season'))
		arr.append([{'stagione':i['season'],'episodi':episodes}])
	print(arr)
	return render(request,'series/episodes.html',{'seasons':arr})

def stream_series(request,id_ep):
	ep = Episode.objects.get(id=id_ep)
	title=ep.title.replace(" ","_")
	filename = ep.series.title+"/"+str(ep.season)+'/'+str(ep.num)+"~"+title+ep.ext
	link = os.path.join(reverse('WatchSeries:series'),settings.SERIES_URL,filename)
	return render(request,'series/stream_series.html',{'episode':ep,'link':link})

AdminPanel/templates/AdminPanel/login.html
 {% extends 'navbar.html' %}
 	{% load bootstrap4 %}
	{% bootstrap_javascript %}
	{% bootstrap_css %}
 {% block content %}
 <form action="{% url 'AdminPanel:login_admin' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
	{% buttons %}
	<button type="submit" class="btn btn-primary">
		Accedi
	</button>
	{% endbuttons %}
    {% if msg %}{% bootstrap_alert msg alert_type='danger' %}{% endif %}
</form>
{% endblock %}

AdminPanel/templates/AdminPanel/main_admin.html
{% extends 'navbar.html' %}
	{% load bootstrap4 %}
	{% bootstrap_javascript %}
	{% bootstrap_css %}
{% block content %}

	<h1>Film</h1>
	<div class="d-inline">
		<div class="col-md-6">
			<h2>Film Inseriti:</h2>
			{% if record_film_inseriti %}
				{% for i in record_film_inseriti %}
					<h3><p>
						{{i.titolo}}
						{% if i.secondo_titolo %} - {{ i.secondo_titolo}}{% endif %}
						{{i.ext}} / 
						{% if i.id_omdb %}
							<font color="green">{{ i.id_omdb }}</font>
						{% else %}
							<font color="red">Nessun id omdb</font>
						{% endif %}
					</p></h3>
				{% endfor %}

			{% else%}
				<h3>Nessuno</h3>
			{% endif %}

		</div>
	</div>

	<div class="d-inline">
		<div class="col-md-6">
			<h2>Film Eliminati</h2>
			{% if record_film_eliminati %}
				{% for i in record_film_eliminati %}
					<font color="red"><h3><p>{{ i.film }}</p></h3></font>
				{% endfor %}

			{% else %}
				<h3>Nessuno</h3>
			{% endif %}
		</div>
	</div>
	{% buttons %}
	<a href="{% url 'AdminPanel:upload_movies' %}">
		<button type="button" class="btn btn-primary">
			Aggiorna Film
		</button>
	</a>
	{% endbuttons %}


	<h2>Aggiunte info</h2>
	{% if arr_movies %}
		{% for i in arr_movies %}
			<h3><p>{{ i.id_imdb}}</p></h3>
		{% endfor %}

	{% else %}
		<h3>Nessuno</h3>
	{% endif %}
	{% buttons %}
	<a href="{% url 'AdminPanel:add_info_movies' %}">
		<button type="button" class="btn btn-primary">
			Aggiorna info Film
		</button>
	</a>
	{% endbuttons %}

	<hr>

	<h1>Serie Tv</h1>
	<div class="d-inline">
		<div class="col-md-6">
			<h2>Serie Aggiunte:</h2>
			{% if serie_aggiunte %}
				{% for i in serie_aggiunte %}
					<h3><p>
						{{ i.titolo }}
						{% if i.id_imdb %}
							<font color="green">{{ i.id_imdb }}</font>
						{% else %}
							<font color="red">Nessun id imdb</font>
						{% endif %}
					</p></h3>
				{% endfor %}

			{% else%}
				<h3>Nessuno</h3>
			{% endif %}

			<h2>Episodi Aggiunti:</h2>
			{% if episodi_aggiunti %}
				{% for i in episodi_aggiunti %}
					<h3><p>Episodio : {{ i.episodio }} - {{ i.titolo }} - Stagione {{ i.stagione }}</p></h3>
				{% endfor %}

			{% else%}
				<h3>Nessuno</h3>
			{% endif %}

		</div>
	</div>

	<div class="d-inline">
		<div class="col-md-6">
			<h2>Serie Eliminate:</h2>
			{% if serie_eliminate %}
				{% for i in serie_eliminate %}
					<font color="red"><h3><p>{{ i.titolo }}</p></h3></font>
				{% endfor %}

			{% else%}
				<h3>Nessuno</h3>
			{% endif %}

			<h2>Episodi Eliminati:</h2>
			{% if episodi_eliminati %}
				{% for i in episodi_eliminati %}
					<font color="red"><h3><p>{{ i.titolo }}</p></h3></font>
				{% endfor %}

			{% else%}
				<h3>Nessuno</h3>
			{% endif %}
		</div>
	</div>
	{% buttons %}
	<a href="{% url 'AdminPanel:upload_series' %}">
		<button type="button" class="btn btn-primary">
			Aggiorna Serie
		</button>
	</a>
	{% endbuttons %}
	

	<h2>Aggiunte info</h2>
	{% if arr_series %}
		{% for i in arr_series %}
			<h3><p>{{ i.id_imdb}}</p></h3>
		{% endfor %}

	{% else %}
		<h3>Nessuno</h3>
	{% endif %}
	{% buttons %}
	<a href="{% url 'AdminPanel:add_info_series' %}">
		<button type="button" class="btn btn-primary">
			Aggiorna info Serie
		</button>
	</a>
	{% endbuttons %}


{% endblock %}

AdminPanel/templates/tutorial.html
{% load bootstrap4 %}
{% bootstrap_javascript %}
{% bootstrap_css %}
	<div class="input-group mb-3">
	  <div class="input-group-prepend">
	    <button class="btn btn-outline-secondary" onclick="copy_to_clipboard()" type="button">Clicca per copiare</button>
	  </div>
	  <input type="text" class="form-control" value="{{link}}" id="link" aria-label="" aria-describedby="basic-addon1">
	</div>
<h2>
	<p>
		Se non riesci a vedere il film , hai problemi con la riproduzione ,oppure vuoi vedere il film con un programma migliore,
        apri il programma vlc media player <img src="https://images.videolan.org/images/icons-VLC/vlc.svg" width="30px" height="35px">.
        Dopo aver atteso l'apertura del programma cliccare In alto a sinistra, nella voce <img src="../Images/media.jpg" width="60px" height="25px">.
        Si aprirà un menù a tendina come il seguente:<img src="Images/flusso_rete.jpg" width="260px" height="250px">
        nel quale dovrete cliccare su "apri flusso di rete".
        Ritornate sul questa pagina e cliccate il tasto destro del mouse sul video , premendo su "Copia l'indirizzo del video" oppure su "Copia indirizzo link".
        In quest'ultima fase , dovrete quindi ri-aprire vlc media player <img src="https://images.videolan.org/images/icons-VLC/vlc.svg" width="30px" height="35px"> in cui vi si presenterà una finestra simile :<img src="../Images/url.jpg" width="600px" height="400px">
        nella quale dovrete incollare il link copiato nel riquadro presente della finestra facendo : tasto destro del mouse e incolla(oppure "paste" se si ha una versione inglese del programma).
        Fatto ciò cliccate "Riproduci".
    </p>
</h2>
<script type="text/javascript">
		function copy_to_clipboard() {
		  var copyText = document.getElementById("link");
		  copyText.select();
		  document.execCommand("Copy");
		}
	</script>

WatchMovie/templates/movies/all.html
{% extends 'navbar.html' %}
{% load bootstrap4 %}
{% bootstrap_javascript %}
{% bootstrap_css %}
{% block content %}
	{% if movies %}
		{% if movies.has_previous %}
			<a href="?p=1">&laquo; Prima pagina</a>
			<a href="?p={{ movies.previous_page_number }}">Precedente</a>
		{% endif %}
		<div class="album py-5 bg-light">
			<div class="container-fluid text-center">
				<div class="row">
					{% for i in movies %}
						<div class="col-md-3">
							<a href="{% url 'WatchMovie:stream_movie' i.id %}">
								<button type="button" class="btn btn-sm btn-outline-secondary" style="border:none;">
									<div class="card md-3 box-shadow">
										<img class="card-img-top mx-auto" src="{{i.img}}" style="height: 100%; width:95%; display: block;">
									</div>
									<div class="card-body">
										<div class="d-flex justify-content-between align-items-center">
		                					<p class="card-text">
		                						{{ i.title }}{% if i.second_title %} - {{ i.second_title }}{% endif %} / {{i.runtime}}
		                					</p>
		                				</div>									
									</div>
								</button>
							</a>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
		<p class="current text-dark">
			Pagina {{ movies.number }} di {{ movies.paginator.num_pages }}.
		</p>
		{% if movies.has_next %}
			<a href="?p={{ movies.next_page_number }}">Prossima</a>
			<a href="?p={{ movies.paginator.num_pages }}">Ultima Pagina &raquo;</a>
		{% endif %}
	{% else %}
		Nessun Risultato
	{%endif%}
{% endblock %}

WatchMovie/templates/movies/index.html
{% extends 'navbar.html' %}
{% load bootstrap4 %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_css %}
{% block content %}
	<form action="{% url 'WatchMovie:search_movie'%}" method="GET" class="form">
	{% bootstrap_form form %}
	{% buttons %}
		<button type="submit" class="btn btn-primary">Submit</button>
	{% endbuttons %}
{% endblock %}

WatchMovie/templates/movies/search.html
{% extends 'navbar.html' %}
{% load bootstrap4 %}
{% bootstrap_javascript %}
{% bootstrap_css %}
{% block content %}
	{% if movies %}
		{% if movies.has_previous %}
		    <a href="?title={{search}}&p=1">&laquo; Prima pagina</a>
		    <a href="?title={{search}}&p={{ movies.previous_page_number }}">Precedente</a>
		{% endif %}
		<div class="album py-5 bg-light">
			<div class="container-fluid text-center">
				<div class="row">
					{% for i in movies %}
						<div class="col-md-3">
							<a href="{% url 'WatchMovie:stream_movie' i.id %}">
								<button type="button" class="btn btn-sm btn-outline-secondary" style="border:none;">
									<div class="card md-3 box-shadow">
										<img class="card-img-top mx-auto" src="{{i.img}}" style="height: 100%; width:95%; display: block;">
									</div>
									<div class="card-body">
										<div class="d-flex justify-content-between align-items-center">
		                					<p class="card-text">
		                						{{ i.title }}{% if i.second_title %} - {{ i.second_title }}{% endif %} / {{i.runtime}}
		                					</p>
		                				</div>									
									</div>
								</button>
							</a>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
		<p class="current text-dark">
			Pagina {{ movies.number }} di {{ movies.paginator.num_pages }}.
		</p>
		{% if movies.has_next %}
	    	<a href="?title={{search}}&p={{ movies.next_page_number }}">Prossima</a>
	    	<a href="?title={{search}}&p={{ movies.paginator.num_pages }}">Ultima Pagina &raquo;</a>
		{% endif %}
	{% else %}
		Nessun Risultato
	{% endif %}	
{% endblock %}

WatchMovie/templates/movies/stream.html
{% extends 'navbar.html' %}
{% load bootstrap4 %}
{% bootstrap_javascript %}
{% bootstrap_css %}
{% block content %}
	<div class="container">
		{% if film %}
			<h1>{{film.title}}{% if film.second_title %} - {{film.second_title}}{%endif%}</h1>
			<video width="800" height="480" poster="{{film.img}}" style="background-color: black !important;" controls>
				<source src="{{link}}">
				Your browser does not support the video tag.
			</video>
			<h3>{{film.runtime}} - {{film.year}}</h3>
			<h4>{{film.plot}}</h4>
			{% include 'tutorial.html' %}
		{% else %}
			<h2>Film non esistente</h2>
		{% endif %}
	</div>
{% endblock %}

WatchMovie/templates/navbar.html
<!DOCTYPE html>
<html>
<head>
	<title>Streaming Server</title>
	{% load bootstrap4 %}
	{% bootstrap_javascript jquery='full'%}
	{% bootstrap_css %}
</head>
<body>
	<nav class="navbar navbar-expand-md navbar-dark bg-dark">
		<div class="collapse navbar-collapse" id="navbarsExampleDefault">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'WatchMovie:index' %}">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'WatchSeries:series' %}">Serie Tv</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'WatchMovie:search_movie' %}">Tutti i Film</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'AdminPanel:login_admin' %}">Pannello Amministratore</a>
				</li>
			</ul>
		</div>
	</nav><br>
		<div class="container-fluid text-center">
			{% block content %}
			{% endblock %}
		</div>
</body>
</html>

WatchSeries/templates/series/episodes.html
{% extends 'navbar.html' %}
{% block content %}
<div class="container">
	{% for k in seasons %}
		{% with k=k.0%}
			<h2>Stagione Numero {{k.stagione}}</h2>
			<div class="list-group">
				{% for i in k.episodi %}
				<a class="list-group-item list-group-item-action" href="{% url 'WatchSeries:stream_series' i.id  %}">
					{{i.num}} - {{i.title}}
				</a>
				{% endfor %}
		{% endwith %}
	{% endfor %}
	</div>
</div>
{% endblock %}

WatchSeries/templates/series/series.html
{% extends 'navbar.html' %}
{% load bootstrap4 %}
{% bootstrap_javascript %}
{% bootstrap_css %}
{% block content %}
	{% if series %}
		{% if series.has_previous %}
			<a href="?p=1">&laquo; Prima pagina</a>
			<a href="?p={{ movies.previous_page_number }}">Precedente</a>
		{% endif %}
		<div class="album py-5 bg-light">
			<div class="container-fluid text-center">
				<div class="row">
					{% for i in series %}
						<div class="col-md-3">
							<a href="{% url 'WatchSeries:episodes' i.id %}">
								<button type="button" class="btn btn-sm btn-outline-secondary" style="border:none;">
									<div class="card md-3 box-shadow">
										<img class="card-img-top mx-auto" src="{{i.img}}" style="height: 100%; width:95%; display: block;">
									</div>
									<div class="card-body">
										<div class="d-flex justify-content-between align-items-center">
		                					<p class="card-text">
		                						{{ i.title }} / {{i.year}}
		                					</p>
		                				</div>									
									</div>
								</button>
							</a>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
		<p class="current text-dark">
			Pagina {{ series.number }} di {{ series.paginator.num_pages }}.
		</p>
		{% if series.has_next %}
			<a href="?p={{ movies.next_page_number }}">Prossima</a>
			<a href="?p={{ movies.paginator.num_pages }}">Ultima Pagina &raquo;</a>
		{% endif %}
	{% else %}
		Nessun Risultato
	{%endif%}
{% endblock %}

WatchSeries/templates/series/stream_series.html
{% extends 'navbar.html' %}
{% load bootstrap4 %}
{% bootstrap_javascript %}
{% bootstrap_css %}
{% block content %}
	<div class="container">
		{% if episode %}
			<h1>Episodio numero {{episode.num}} Stagione {{episode.season}}</h1>
			<video width="800" height="480" poster="{{episode.series.img}}" style="background-color: black !important;" controls>
				<source src="{{link}}" >
				Your browser does not support the video tag.
			</video>
			{% include 'tutorial.html' %}
		{% else %}
			<h2>Episodio non esistente!</h2>
		{% endif %}
	</div>
{% endblock %}